name: build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - name: Setup Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # pin@v3
        with:
          go-version-file: go.mod

      - name: Setup Git
        run: |
          git config user.name "Test User"
          git config user.email "test-user@example.com"

      - name: Test
        run: make test

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # pin@v3

      - name: Setup Go
        uses: actions/setup-go@c4a742cab115ed795e34d4513e2cf7d472deb55f # pin@v3
        with:
          go-version-file: go.mod

      - name: golangci-lint
        uses: golangci/golangci-lint-action@07db5389c99593f11ad7b44463c2d4233066a9b1 # pin@v3
        with:
          version: v1.49
          only-new-issues: true
