name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # pin@v2
      - uses: cli/gh-extension-precompile@ea409c0dc27ec3031d1b0d18d17124441d3c3b6b # pin@v1
